import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { AlertTriangle } from "lucide-react";

export async function generateMetadata() {
    const t = await getTranslations("staticPages.disclaimer");
    return {
        title: "Medical Disclaimer",
        description: t("subtitle"),
    };
}

const POINTS = [
    {
        title: "Not a medical service",
        body: "MindEase is a technology platform that connects you with licensed psychologists and provides wellness tools. It does not diagnose, treat, cure, or prevent any medical or psychological condition.",
    },
    {
        title: "AI content is guidance only",
        body: "AI-generated content — including pre-session questions, clinical briefings, and wellness suggestions — is generated by artificial intelligence for guidance and preparation purposes only. It is not a diagnosis, medical advice, or a treatment plan. Always discuss your situation with your licensed psychologist.",
    },
    {
        title: "Not an emergency service",
        body: "MindEase is not an emergency or crisis service. If you are in immediate danger of harming yourself or others, call your local emergency number now — in Indonesia dial 112 or 119. See our crisis hotlines for free 24/7 support.",
    },
    {
        title: "Psychologists are independent professionals",
        body: "Psychologists on MindEase are independent licensed professionals. The clinical care, advice, and treatment they provide is their professional responsibility — MindEase facilitates the connection but does not direct their clinical judgment.",
    },
    {
        title: "Seek professional care",
        body: "The content on this platform is not a substitute for professional consultation. If you have concerns about your mental or physical health, please consult a qualified healthcare professional in person.",
    },
];

export default async function DisclaimerPage() {
    const t = await getTranslations("staticPages.disclaimer");
    return (
        <main className="min-h-screen bg-gray-50">
            <div className="max-w-4xl mx-auto px-4 md:px-8 py-20">
                <div className="bg-white rounded-[2rem] border border-gray-100 shadow-sm p-8 md:p-12 mb-10">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="w-12 h-12 rounded-2xl bg-amber-100 flex items-center justify-center">
                            <AlertTriangle className="w-6 h-6 text-amber-600" />
                        </div>
                        <span className="text-sm font-black uppercase tracking-widest text-amber-600">Medical Disclaimer</span>
                    </div>
                    <h1 className="text-4xl md:text-5xl font-black text-gray-900 font-outfit mb-4">
                        {t("title")} <span className="text-amber-600">{t("titleAccent")}</span>
                    </h1>
                    <p className="text-gray-500">
                        {t("subtitle")}
                    </p>
                </div>

                <div className="space-y-8 mb-10">
                    {POINTS.map((p) => (
                        <div key={p.title} className="bg-white rounded-3xl border border-gray-100 p-8">
                            <h2 className="text-xl font-extrabold text-gray-900 mb-3">{p.title}</h2>
                            <p className="text-gray-600 leading-relaxed">{p.body}</p>
                        </div>
                    ))}
                </div>

                <div className="bg-rose-50 border border-rose-200 rounded-3xl p-8 text-center">
                    <h2 className="text-lg font-extrabold text-rose-700 mb-2">Need urgent help right now?</h2>
                    <p className="text-rose-600 mb-5">
                        MindEase is not an emergency service. Call 112 (Indonesia) or a hotline immediately.
                    </p>
                    <Link
                        href="/crisis"
                        className="inline-block px-8 py-3.5 bg-rose-600 text-white rounded-2xl font-black hover:bg-rose-700 transition-all"
                    >
                        View Crisis Hotlines
                    </Link>
                </div>
            </div>
        </main>
    );
}
