// Creates and validates the local environment files.
//
// ## Why this exists
//
// `make setup` advertised itself as "create the env files". It created one file,
// from a template, with placeholder secrets, and printed two notes about the two
// files that actually matter. Nothing generated a signing secret, and nothing
// checked that the API and the web app agreed on one.
//
// The failure that follows is silent and very confusing. `client/proxy.ts`
// verifies the `accessToken` cookie with the client's `JWT_SECRET`; the API signs
// it with the server's. When they differ, sign-in succeeds - the API answers 200,
// the profile request answers 200 - and then the browser is bounced straight back
// to `/login?next=/dashboard` by the proxy, which cannot verify a token signed
// with a secret it does not have. The user sees a login form that accepts their
// password and then does nothing, forever.
//
// There is also a second thing this script had to correct: `server/src/index.ts`
// calls `dotenv.config()` with no path, so the API reads `server/.env`. The
// Makefile's `env` target told the reader the opposite - "the server reads the
// root .env" - and created a root `.env` that nothing loads.
//
// Usage:
//
//     node scripts/setup-env.js           # create what is missing, never overwrite
//     node scripts/setup-env.js --check   # validate, exit 1 on a problem
//
// Secrets are never printed. Comparisons are reported as a short digest.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.join(__dirname, "..");
const EXAMPLE = path.join(ROOT, ".env.example");
const SERVER_ENV = path.join(ROOT, "server", ".env");
const CLIENT_ENV = path.join(ROOT, "client", ".env.local");

/** Secrets that must be generated rather than shipped as placeholders. */
const GENERATED = ["JWT_SECRET", "REFRESH_SECRET", "TWO_FACTOR_SECRET"];

/** Placeholder values from .env.example that must never survive into a real env. */
const PLACEHOLDERS = [
  "dev_replace_me_access_secret",
  "dev_replace_me_refresh_secret",
  "dev_replace_me_two_factor_secret",
];

/**
 * Client variables the build inlines. `NEXT_PUBLIC_API_URL` is the one that
 * matters most: `lib/api.ts` falls back to `http://localhost:5000/api`, and the
 * CSP is derived from the same variable, so an unset value silently disagrees
 * with the header if the fallback ever changes.
 */
const CLIENT_VARS = [
  { name: "NEXT_PUBLIC_API_URL", value: "http://localhost:5000/api" },
  { name: "NEXT_PUBLIC_REALTIME_URL", value: "ws://localhost:8080/ws" },
  { name: "NEXT_PUBLIC_SITE_URL", value: "http://localhost:3000" },
  { name: "NEXT_PUBLIC_GOOGLE_CLIENT_ID", value: "" },
  { name: "NEXT_PUBLIC_SENTRY_DSN", value: "" },
];

/** A short, non-reversible fingerprint, so two secrets can be compared safely. */
function digest(s) {
  return crypto.createHash("sha256").update(s).digest("hex").slice(0, 10);
}

function read(file) {
  try {
    return fs.readFileSync(file, "utf8");
  } catch {
    return null;
  }
}

/** Pull `KEY=VALUE` out of a dotenv file. Quoted and commented forms included. */
function parseEnv(text) {
  const out = new Map();
  for (const line of (text || "").split(/\r?\n/)) {
    const m = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line);
    if (!m) continue;
    let v = m[2].trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1);
    }
    out.set(m[1], v);
  }
  return out;
}

/** A 48-byte base64 secret. 64 characters, matching the `openssl rand -base64 48` the README documents. */
const newSecret = () => crypto.randomBytes(48).toString("base64");

// ---------------------------------------------------------------- create ----

function buildServerEnv(jwtSecret) {
  let text = read(EXAMPLE);
  if (!text) throw new Error(".env.example is missing");
  for (const key of GENERATED) {
    const value = key === "JWT_SECRET" && jwtSecret ? jwtSecret : newSecret();
    const re = new RegExp(`^${key}=.*$`, "m");
    text = re.test(text) ? text.replace(re, `${key}=${value}`) : `${text}\n${key}=${value}\n`;
  }
  return text;
}

function buildClientEnv(jwtSecret) {
  const lines = [
    "# Generated by `node scripts/setup-env.js`. Safe to edit; safe to delete and regenerate.",
    "",
    "# Must be byte-identical to JWT_SECRET in server/.env.",
    "#",
    "# `client/proxy.ts` verifies the accessToken cookie with this value. If it",
    "# differs from the API's signing secret, sign-in returns 200, the profile",
    "# request returns 200, and the proxy bounces the user back to /login with no",
    "# message - because it cannot verify a token signed with a secret it does",
    "# not have. That is the whole symptom of getting this wrong.",
    `JWT_SECRET=${jwtSecret}`,
    "",
    "# Inlined at build time, and also the source of the CSP connect-src list.",
  ];
  for (const v of CLIENT_VARS) lines.push(`${v.name}=${v.value}`);
  lines.push("");
  return lines.join("\n");
}

/**
 * Write a file only if it does not exist, atomically.
 *
 * The previous version did `if (!fs.existsSync(p)) fs.writeFileSync(p, ...)`.
 * That is a time-of-check/time-of-use race: anything that created the file between
 * the check and the write would have it silently overwritten, and for this
 * particular file that means silently overwriting a **signing secret**. CodeQL's
 * "potential file system race condition" query is right about the shape even
 * though nobody is racing this script in practice.
 *
 * `flag: "wx"` is the correct primitive rather than a mitigation: the open is
 * exclusive and fails with `EEXIST`, so there is no window in which the file can
 * be replaced. The race stops existing rather than becoming unlikely.
 *
 * @returns {boolean} true if this call created the file
 */
function createIfAbsent(file, contents) {
  try {
    fs.writeFileSync(file, contents, { encoding: "utf8", flag: "wx" });
    return true;
  } catch (e) {
    if (e && e.code === "EEXIST") return false;
    throw e;
  }
}

function create() {
  const actions = [];

  if (createIfAbsent(SERVER_ENV, buildServerEnv(newSecret()))) {
    actions.push("created server/.env with freshly generated secrets");
  } else {
    actions.push("kept server/.env (already exists, not overwritten)");
  }

  const serverEnv = parseEnv(read(SERVER_ENV));
  const jwt = serverEnv.get("JWT_SECRET");

  if (createIfAbsent(CLIENT_ENV, buildClientEnv(jwt || newSecret()))) {
    actions.push("created client/.env.local with a matching JWT_SECRET");
  } else {
    actions.push("kept client/.env.local (already exists, not overwritten)");
  }

  const rootEnv = path.join(ROOT, ".env");
  if (!fs.existsSync(rootEnv)) {
    actions.push(
      "NOTE: no root .env. server/src/index.ts calls dotenv.config(), which reads " +
        "server/.env only - a root .env is not loaded by the API."
    );
  }

  return actions;
}

// ----------------------------------------------------------------- check ----

function check() {
  const problems = [];
  const notes = [];

  if (!fs.existsSync(SERVER_ENV)) {
    problems.push("server/.env does not exist - `node scripts/setup-env.js` creates it");
    return { problems, notes };
  }

  const serverEnv = parseEnv(read(SERVER_ENV));
  const serverJwt = serverEnv.get("JWT_SECRET");

  if (!serverJwt) {
    problems.push("server/.env has no JWT_SECRET");
  } else if (PLACEHOLDERS.includes(serverJwt)) {
    problems.push(
      `server/.env JWT_SECRET is still the .env.example placeholder (${digest(serverJwt)}) - ` +
        "every token is signed with a published string"
    );
  }

  for (const key of GENERATED) {
    const v = serverEnv.get(key);
    if (!v) problems.push(`server/.env has no ${key}`);
    else if (PLACEHOLDERS.includes(v)) problems.push(`server/.env ${key} is still the placeholder`);
  }

  if (!fs.existsSync(CLIENT_ENV)) {
    problems.push(
      "client/.env.local does not exist - without it the client builds with its " +
        "fallback API URL and the CSP allows a different origin"
    );
    return { problems, notes };
  }

  const clientEnv = parseEnv(read(CLIENT_ENV));
  const clientJwt = clientEnv.get("JWT_SECRET");

  if (!clientJwt) {
    problems.push("client/.env.local has no JWT_SECRET");
  } else if (serverJwt && clientJwt !== serverJwt) {
    problems.push(
      "JWT_SECRET differs between server/.env and client/.env.local " +
        `(server ${digest(serverJwt)}, client ${digest(clientJwt)}). ` +
        "Sign-in will appear to succeed and then bounce back to /login, because " +
        "client/proxy.ts cannot verify a token signed with the server's secret."
    );
  }

  for (const v of CLIENT_VARS) {
    if (!clientEnv.has(v.name)) {
      problems.push(`client/.env.local has no ${v.name}`);
    }
  }

  const api = clientEnv.get("NEXT_PUBLIC_API_URL");
  if (api) {
    try {
      const u = new URL(api);
      if (!/^https?:$/.test(u.protocol)) problems.push(`NEXT_PUBLIC_API_URL is not http(s): ${api}`);
    } catch {
      problems.push(`NEXT_PUBLIC_API_URL is not a URL: ${api}`);
    }
  }

  const realtime = clientEnv.get("NEXT_PUBLIC_REALTIME_URL");
  if (realtime) {
    try {
      const u = new URL(realtime);
      if (!/^(ws|wss|https?):$/.test(u.protocol)) {
        problems.push(`NEXT_PUBLIC_REALTIME_URL is not ws/wss/http(s): ${realtime}`);
      }
    } catch {
      problems.push(`NEXT_PUBLIC_REALTIME_URL is not a URL: ${realtime}`);
    }
  }

  if (fs.existsSync(path.join(ROOT, ".env"))) {
    notes.push(
      "a root .env exists but server/src/index.ts uses dotenv.config(), which reads " +
        "server/.env. Changes to the root .env have no effect on the API."
    );
  }

  return { problems, notes };
}

// ------------------------------------------------------------------ main ----

const isCheck = process.argv.includes("--check");

if (isCheck) {
  const { problems, notes } = check();
  for (const n of notes) console.log(`  note: ${n}`);
  if (problems.length) {
    console.error(`setup-env check found ${problems.length} problem(s):\n`);
    for (const p of problems) console.error(`  ${p}`);
    console.error("");
    process.exit(1);
  }
  console.log("  env                  ok (secrets generated, client and server agree)");
} else {
  if (!fs.existsSync(EXAMPLE)) {
    console.error(".env.example is missing; nothing to do");
    process.exit(1);
  }
  for (const a of create()) console.log(`  ${a}`);
}